version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/narou-react"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    eslint:
      patterns:
      - "@typescript-eslint/*"
      - "eslint-*"
      - "eslint"
    mui:
      patterns:
      - "@mui/*"
    react:
      patterns:
      - "@types/react-*"
      - "@types/react"
      - "react-*"
      - "react"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
