version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/narou-react"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jest"
    versions:
    - 26.0.23
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
