name: Update Visual Snapshots on Main

on:
  push:
    branches: [main]
    paths:
      - "narou-react/src/**/*.tsx"
      - "narou-react/src/**/*.ts"
      - "!narou-react/src/**/*.test.tsx"
      - "!narou-react/src/**/*.test.ts"

permissions:
  contents: write

defaults:
  run:
    working-directory: narou-react

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "narou-react/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Update Visual Snapshots
        run: npm run test:visual:update

      - name: Check for changes
        id: verify-changed-files
        working-directory: .
        run: |
          if git diff --quiet narou-react/src/**/__screenshots__; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Updated Snapshots
        if: steps.verify-changed-files.outputs.changed == 'true'
        working-directory: .
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add narou-react/src/**/__screenshots__
          git commit -m "chore: update visual regression snapshots [skip ci]"
          git push

      - name: No changes
        if: steps.verify-changed-files.outputs.changed == 'false'
        run: echo "✅ No snapshot changes needed"
