name: Update Visual Snapshots on Main

on:
  push:
    branches: [main]
    paths:
      - "narou-react/src/**/*.tsx"
      - "narou-react/src/**/*.ts"
      - "!narou-react/src/**/*.test.tsx"
      - "!narou-react/src/**/*.test.ts"

permissions:
  contents: write

defaults:
  run:
    working-directory: narou-react

jobs:
  update-snapshots:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "narou-react/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        working-directory: narou-react
        run: echo "version=$(npm list playwright --json | jq -r '.dependencies.playwright.version')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium --only-shell

      - name: Install Playwright dependencies only
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
            libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
            libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
            libgbm1 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0 \
            libxshmfence1 libglib2.0-0

      - name: Update Visual Snapshots
        run: npm run test:visual:update

      - name: Check for changes
        id: verify-changed-files
        working-directory: .
        run: |
          if git diff --quiet narou-react/src/**/__screenshots__; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Updated Snapshots
        if: steps.verify-changed-files.outputs.changed == 'true'
        working-directory: .
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add narou-react/src/**/__screenshots__
          git commit -m "chore: update visual regression snapshots [skip ci]"
          git push

      - name: No changes
        if: steps.verify-changed-files.outputs.changed == 'false'
        run: echo "✅ No snapshot changes needed"
